// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjCFYAEznB6E43WUMfcR_cbpUa8DxSM7E',
    appId: '1:427670214780:web:4b3b2bc134aaa8793751f9',
    messagingSenderId: '427670214780',
    projectId: 'brainfood-4d3eb',
    authDomain: 'brainfood-4d3eb.firebaseapp.com',
    storageBucket: 'brainfood-4d3eb.appspot.com',
    measurementId: 'G-FK77QZQGSC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7YGgvEuSv4ppm8EAwEuCHT7VsKrC_ESo',
    appId: '1:427670214780:android:5585c4bbd2b973513751f9',
    messagingSenderId: '427670214780',
    projectId: 'brainfood-4d3eb',
    storageBucket: 'brainfood-4d3eb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMCZ3HS1kNoDhb7Kg7OFqzs_W8GE19dYI',
    appId: '1:427670214780:ios:bab72b65a68c91673751f9',
    messagingSenderId: '427670214780',
    projectId: 'brainfood-4d3eb',
    storageBucket: 'brainfood-4d3eb.appspot.com',
    iosClientId: '427670214780-rfp95c4bmd90t3lo4ghq2a6am630thm6.apps.googleusercontent.com',
    iosBundleId: 'com.birigu.brainfood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMCZ3HS1kNoDhb7Kg7OFqzs_W8GE19dYI',
    appId: '1:427670214780:ios:bab72b65a68c91673751f9',
    messagingSenderId: '427670214780',
    projectId: 'brainfood-4d3eb',
    storageBucket: 'brainfood-4d3eb.appspot.com',
    iosClientId: '427670214780-rfp95c4bmd90t3lo4ghq2a6am630thm6.apps.googleusercontent.com',
    iosBundleId: 'com.birigu.brainfood',
  );
}
